### PR TITLE
Add support for Rails 7.1

### PR DESCRIPTION
**Pull request by pyromaniac**
Hey @ka8725, thanks for a great gem.

### CODE REVIEW

**Comment by pyromaniac** [comment]
Ok, it looks like Rails 6.0 is not supported by the current implementation since `ActiveRecord::MigrationProxy` is a simple struct there and doesn't have the role yet.

**Comment by ka8725** [comment]
@pyromaniac does that mean it didn't work with Rails 6.0 even before your changes? I prefer to fix it in a separate ticket. Thanks for your contribution. This work is fantastic!

**Review by ka8725 — APPROVED** [review]

**Comment by ka8725** [comment]
Ticket created https://github.com/widefix/actual_db_schema/issues/31

**Comment by pyromaniac** [comment]
@ka8725 it appear so to me. Thanks for merging this quickly!

**Pull request merged**
